package org.cis1200;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.io.FileReader;
import java.io.IOException;
import java.time.Duration;

import java.io.BufferedReader;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** Tests for TwitterBot class */
public class TwitterBotTest {

    /*
     * The below test cases test whether your TwitterBot class itself is written
     * correctly. To generate a tweet of specific content, make a desiredTweet list
     * containing the words you want to appear in the tweet. Then, call
     * fixDistribution on desiredTweet. This should make your twitter bot generate
     * the desired tweet as a string when you call generateTweet with the length of
     * your tweet content (not including punctuations).
     *
     * These tests operate very similarly to our MarkovChain tests in its use of
     * `fixDistribution`, so make sure you know how to test MarkovChain before
     * testing this!
     */
    @Test
    public void simpleTwitterBotShortTest() {
        List<String> desiredTweet = new ArrayList<>(
                Arrays.asList(
                        "hello", "cis1200", "world", "!"
                )
        );
        String words = "0, simple test.\n"
                + "1, hello cis1200 world!\n"
                + "2, this is amazing.";
        StringReader sr = new StringReader(words);
        BufferedReader br = new BufferedReader(sr);
        TwitterBot t = new TwitterBot(br, 1);
        t.fixDistribution(desiredTweet);

        String expected = "hello cis1200 world!";
        String actual = t.generateTweet(3);
        assertEquals(expected, actual);
    }

    @Test
    public void simpleTwitterBotLongTest() {
        List<String> desiredTweet = new ArrayList<>(
                Arrays.asList(
                        "this", "comes", "from", "data", "with", "no", "duplicate", "words", ".",
                        "the", "end", "should", "come", "."
                )
        );
        String words = "0, The end should come here.\n"
                + "1, This comes from data with no duplicate words!";
        StringReader sr = new StringReader(words);
        BufferedReader br = new BufferedReader(sr);
        TwitterBot t = new TwitterBot(br, 1);
        t.fixDistribution(desiredTweet);

        String expected = "this comes from data with no duplicate words. the end should come.";
        String actual = TweetParser.replacePunctuation(t.generateTweet(12));
        assertEquals(expected, actual);
    }

    /*
     * This is the empty file test case.
     *
     * When your CSV file is empty, your program should create an empty MarkovChain.
     * An empty tweet should be generated by your bot.
     * No exceptions should be thrown and your program should not go into an
     * infinite loop!
     */
    @Test
    public void emptyFileCreatesEmptyTweet() {
        // Checks that your program does not go into an infinite loop
        assertTimeoutPreemptively(
                Duration.ofSeconds(10), () -> {
                    // No exceptions are thrown if file is empty
                    TwitterBot tb = new TwitterBot(
                            FileLineIterator.fileToReader("./files/empty.csv"), 2
                    );
                    // Checks that the bot creates an empty tweet
                    assertEquals(0, tb.generateTweet(10).length());
                }
        );
    }

    /* **** ****** **** WRITE YOUR TESTS BELOW THIS LINE **** ****** **** */
    // Note: make sure to test for punctuations using `isPunctuated`.

    @Test
    public void fixDistributionWithPunctuationInTweet() {
        List<String> desiredTweet = new ArrayList<>(
                Arrays.asList(
                        "hello", "world", "!"
                )
        );
        String words = "0, Hello world!";
        StringReader sr = new StringReader(words);
        BufferedReader br = new BufferedReader(sr);
        TwitterBot t = new TwitterBot(br, 1);
        t.fixDistribution(desiredTweet);
        assertEquals("hello world!", t.generateTweet(2));
    }

    @Test
    public void testPunctuationIsAddedIfMissing() {
        List<String> desiredTweet = Arrays.asList("hello", "cis1200", "!");
        String words = "0, hello cis1200";
        StringReader sr = new StringReader(words);

        BufferedReader br = new BufferedReader(sr);
        TwitterBot tb = new TwitterBot(br, 1);
        tb.fixDistribution(desiredTweet);

        String tweet = tb.generateTweet(2);
        assertTrue(TwitterBot.isPunctuated(tweet));
        assertEquals("hello cis1200!", tb.generateTweet(2));

        assertThrows(IllegalArgumentException.class, () -> {
            tb.generateTweet(-1);
        });
    }

    @Test
    public void testWritingTweetsToFile() {
        List<String> desiredTweet = Arrays.asList("have", "a", "nice", "day", ".");
        String words = "0, have a nice day";
        StringReader sr = new StringReader(words);
        BufferedReader br = new BufferedReader(sr);

        TwitterBot tb = new TwitterBot(br, 1);
        tb.fixDistribution(desiredTweet);

        tb.writeTweetsToFile(5, 50, "test.txt", false);

        List<String> tweets = new ArrayList<>();
        try {
            BufferedReader reader = new BufferedReader(new FileReader("test.txt"));
            String line;
            while ((line = reader.readLine()) != null) {
                tweets.add(line);
            }
            reader.close();
        } catch (IOException e) {
            e.getMessage();
        }

        assertEquals(5, tweets.size());
        for (String tweet : tweets) {
            assertTrue(TwitterBot.isPunctuated(tweet));
            assertEquals(50, tweet.length());
        }
    }

}
